# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bindu
tagline:          'An unknown'
description:      'One place to find my musings'
url:              http://youbee.in
baseurl:          /

author:
  name:           'Bindu Upadhyay'
  url:            https://twitter.com/upadhyaybindu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/UpadhyayBindu
